#!/bin/bash -eu

sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"

$SNAP_COMPONENTS/model-30b-a3b-q4-k-m-gguf-1-of-6/init

exec "$SNAP_COMPONENTS/llama-cpp/server" --sleep-idle-seconds "$sleep_idle_seconds"
