name: nemotron-3-nano
base: core24
summary: Inference Snap for NemotronNano330BA3B
description: |
  This is an inference snap that lets you run NemotronNano330BA3B model using CPU.

adopt-info: version

grade: devel
confinement: strict 
compression: lzo

environment:
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR

hooks:
  install:
    plugs:
      - hardware-observe
      - opengl

parts:
  version:
    plugin: dump
    source: .
    build-packages:
      - git-lfs
    override-pull: |
      craftctl set version="v3+$(git -C $SNAPCRAFT_PROJECT_DIR describe --always --dirty)"
      
  cli:
    source: https://github.com/canonical/inference-snaps-cli.git
    source-tag: v1.0.0-beta.24
    plugin: go
    build-snaps:
      - go/1.24/stable
    stage-packages:
      - pciutils
      - clinfo
    organize:
      bin/cli: bin/modelctl

  component-local-files:
    plugin: dump
    source: components
    organize:
      "llama-cpp": (component/llama-cpp)
      "nemotoron-nano3-30b": (component/nemotoron-nano3-30b)

  engines:
    source: engines
    plugin: dump
    organize:
      "*": engines/

  scripts:
    source: scripts
    plugin: dump
    organize:
      "*": bin/

  common-runtime-dependencies:
    plugin: nil
    stage-snaps:
      - jq

  llama-cpp:
    plugin: dump
    source: 
      - on amd64: https://github.com/jpm-canonical/llama.cpp-builds/releases/download/b7728/llamacpp-amd64.tar.gz
      - on arm64: https://github.com/jpm-canonical/llama.cpp-builds/releases/download/b7728/llamacpp-arm64.tar.gz
    stage-packages:
      - libgomp1
    organize:
      "*": (component/llama-cpp)

components: 
  nemotoron-nano3-30b:
    type: standard
    summary: NVIDIA Nemotron-Nano-3-30B-A3B-Q4_K_M GGUF
    description: 30B parameter LLM model in GGUF format optimized for CPU inference

  llama-cpp:
    type: standard
    summary: llama.cpp HTTP server
    description: Optimized for inference on CPUs

apps:
  nemotron-3-nano:
    command: bin/modelctl
    plugs:
      - hardware-observe
      - opengl
      - network

  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - network-bind
      - hardware-observe
      - opengl

