#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.install"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Set generic config
#

modelctl set --package verbose="false"

# Main server http config
modelctl set --package http.port="8330"
modelctl set --package http.host="127.0.0.1"

# Webui server config
modelctl set --package webui.http.port="8331"
modelctl set --package webui.http.host="127.0.0.1"

#
# Auto select an engine
#

modelctl use-engine --auto --assume-yes --fallback=cpu
