#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.post-refresh"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# New default configurations
#
# Set default configurations for new options added after the initial release.
# This ensures that default values are present in upgraded snaps.
if ! modelctl get webui &> /dev/null; then
    modelctl set --package webui.http.port="8331"
    modelctl set --package webui.http.host="127.0.0.1"
fi

# Refresh the active engine
# This involves applying changes to configurations and required snap components.
# If the active engine has been removed, another engine will be auto selected.
# The automatic selection requires access to hardware information on the system.
if snapctl is-connected hardware-observe; then
    modelctl use-engine --fix --assume-yes --verbose
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --fix --assume-yes --verbose
else
    echo "hardware-observe interface not connected. Skip fixing the active engine."
fi
